# Generated by Django 4.2.7 on 2023-12-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerApp', '0007_delete_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolism', models.CharField(max_length=255)),
                ('discount_quantity', models.FloatField()),
            ],
        ),
    ]
