# Generated by Django 4.2.7 on 2023-12-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerApp', '0008_discountcoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
