# Generated by Django 4.2.7 on 2023-12-14 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courierApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courier',
        ),
    ]
