# Generated by Django 4.2.7 on 2023-12-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0043_courier_alter_order_courier'),
        ('courierApp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courier',
        ),
    ]
