# Generated by Django 4.2.7 on 2023-12-15 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0051_alter_order_courier'),
        ('courierApp', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courier',
        ),
    ]
