# Generated by Django 4.2.7 on 2023-11-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_name',
        ),
    ]
