# Generated by Django 4.2.7 on 2023-11-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerApp', '0006_product_slug'),
        ('clientApp', '0002_remove_client_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.ManyToManyField(blank=True, null=True, to='sellerApp.product'),
        ),
    ]
