# Generated by Django 4.2.7 on 2023-11-30 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0003_remove_cart_product_id_cart_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='clientApp.client'),
        ),
    ]
