# Generated by Django 4.2.7 on 2023-12-01 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientApp', '0005_remove_cart_products_alter_cart_client_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
