# Generated by Django 4.2.7 on 2023-12-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerApp', '0007_delete_seller'),
        ('clientApp', '0006_alter_cart_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='sellerApp.product'),
        ),
    ]
