# Generated by Django 4.2.7 on 2023-12-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0007_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='general_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
