# Generated by Django 4.2.7 on 2023-12-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0009_currentorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='currentorder',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
