# Generated by Django 4.2.7 on 2023-12-10 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0010_alter_client_options_alter_currentorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_date', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientApp.client')),
                ('orders', models.ManyToManyField(to='clientApp.currentorder')),
            ],
        ),
    ]
