# Generated by Django 4.2.7 on 2023-12-11 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0017_alter_orderhistory_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentorder',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientApp.cart'),
        ),
    ]
