# Generated by Django 4.2.7 on 2023-12-11 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0018_alter_currentorder_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientApp.client'),
        ),
    ]
