# Generated by Django 4.2.7 on 2023-12-11 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0019_alter_currentorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientApp.cart'),
        ),
    ]
