# Generated by Django 4.2.7 on 2023-12-12 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0021_remove_orderhistory_cart_orderhistoryitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='orders',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientApp.currentorder'),
        ),
    ]
