# Generated by Django 4.2.7 on 2023-12-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0023_remove_orderhistoryitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistoryitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='OrderHistory',
        ),
        migrations.DeleteModel(
            name='OrderHistoryItem',
        ),
    ]
