# Generated by Django 4.2.7 on 2023-12-12 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerApp', '0009_alter_product_discount'),
        ('clientApp', '0024_remove_orderhistoryitem_order_delete_orderhistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sellerApp.product'),
        ),
    ]
