# Generated by Django 4.2.7 on 2023-12-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerApp', '0009_alter_product_discount'),
        ('clientApp', '0025_remove_cart_products_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='sellerApp.product'),
        ),
    ]
