# Generated by Django 4.2.7 on 2023-12-13 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerApp', '0009_alter_product_discount'),
        ('clientApp', '0026_remove_cart_products_cart_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrentOrder',
            new_name='Order',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clientApp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellerApp.product')),
            ],
        ),
    ]
