# Generated by Django 4.2.7 on 2023-12-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0030_remove_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
