# Generated by Django 4.2.7 on 2023-12-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0031_remove_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
