# Generated by Django 4.2.7 on 2023-12-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0033_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ожидание', 'waiting'), ('Одобренно', 'approved'), ('Отказано', 'denied')], default='Ожидание', max_length=15),
        ),
    ]
