# Generated by Django 4.2.7 on 2023-12-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0036_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ожидание', 'waiting'), ('Одобренно', 'approved'), ('Отказано', 'approved'), ('Доставлено', 'delivered')], default='Ожидание', max_length=15),
        ),
    ]
