# Generated by Django 4.2.7 on 2023-12-14 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientApp', '0037_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ManyToManyField(null=True, related_name='order_as_courier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ожидание', 'waiting'), ('Одобренно', 'approved'), ('Отказано', 'approved'), ('Принято', 'accepted'), ('Доставлено', 'delivered')], default='Ожидание', max_length=15),
        ),
    ]
