# Generated by Django 4.2.7 on 2023-12-15 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courierApp', '0003_initial'),
        ('clientApp', '0039_remove_order_courier_order_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_as_courier', to='courierApp.courier'),
        ),
    ]
