# Generated by Django 4.2.7 on 2023-12-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courierApp', '0003_initial'),
        ('clientApp', '0040_alter_order_courier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='courier',
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ManyToManyField(blank=True, null=True, related_name='order_as_courier', to='courierApp.courier'),
        ),
    ]
