# Generated by Django 4.2.7 on 2023-12-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courierApp', '0003_initial'),
        ('clientApp', '0041_remove_order_courier_order_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ManyToManyField(null=True, related_name='order_as_courier', to='courierApp.courier'),
        ),
    ]
