# Generated by Django 4.2.7 on 2023-12-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0045_alter_order_courier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='courier',
        ),
    ]
