# Generated by Django 4.2.7 on 2023-12-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0046_remove_order_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ManyToManyField(null=True, to='clientApp.courier'),
        ),
    ]
