# Generated by Django 4.2.7 on 2023-12-15 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0048_remove_order_courier_order_courier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='user_ptr',
        ),
    ]
