# Generated by Django 4.2.7 on 2023-12-15 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courierApp', '0005_initial'),
        ('clientApp', '0049_remove_courier_user_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courierApp.courier'),
        ),
        migrations.DeleteModel(
            name='Courier',
        ),
    ]
